apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      certificate-authority-data: ZHVtbXk=
      server: https://127.0.0.1
    name: dummy

current-context: dummy

contexts:
  - context:
      cluster: dummy
      user: dummy
    name: dummy

users:
  - name: dummy
    user:
      token: ZHVtbXk=