// Code generated by hashicorp/terraform-plugin-codegen-kubernetes; DO NOT EDIT
//
// This file contains the list of constructors for resources that have been autogenerated.
//
// This code was written by a robot on Jul 29, 2024 23:46:42 UTC.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/hashicorp/terraform-provider-kubernetes/internal/framework/provider/corev1"
	"github.com/hashicorp/terraform-provider-kubernetes/internal/framework/provider/rbacv1"
)

var generatedResources = []func() resource.Resource{
	corev1.NewConfigMap,
	corev1.NewNamespace,
	corev1.NewSecret,
	corev1.NewService,
	corev1.NewServiceAccount,
	rbacv1.NewRole,
	rbacv1.NewRoleBinding,
}
