// Code generated by internal/framework/codegen; DO NOT EDIT
//
// This file contains the list of constructors for resources that have been autogenerated.
//
// This code was written by a robot on Feb 23, 2024 09:04:32 UTC.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/hashicorp/terraform-provider-kubernetes/internal/framework/provider/v1"
)

var generatedResources = []func() resource.Resource{
	v1.NewSecret,
}
