// Code generated by tools/gen/schema_openapi_v3.go; DO NOT EDIT
//
// This file contains the list of constructors for resources that have been autogenerated.
//
// This code was written by a robot on Nov 29, 2023 21:21:28 UTC.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

var generatedResources = []func() resource.Resource{}
