// Code generated by hashicorp/terraform-plugin-codegen-kubernetes; THIS FILE IS FOR YOU TO EDIT
//
// This file contains function signatures for implementing CRUD hooks.
// You need to provide the implementation for these functions.
//
// This code was written by a robot on Mar 26, 2024 15:25:45 UTC.

package corev1

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func (r *Secret) BeforeCreate(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse, m *SecretModel) {
	// TODO: Add BeforeCreate logic
}
