name: Deferred Actions

on:
  pull_request:
    branches:
      - main
      - v3-major-release
    paths:
      - "manifest/**/*.go"
      - 'kubernetes/**/*.go'
      - "go.mod"
  workflow_dispatch:
    inputs:
      terraformVersion:
        description: Terraform version
        default: 1.12.0-alpha20250312

env:
  TERRAFORM_VERSION: ${{ github.event.inputs.terraformVersion || '1.12.0-alpha20250312' }}

jobs:
  acceptance_tests:
    if: ${{ github.repository_owner == 'hashicorp' }}
    runs-on: custom-linux-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Run Tests
        env:
          TF_ACC: 1
          # Do not set TF_ACC_TERRAFORM_PATH or TF_ACC_TERRAFORM_VERSION.
          # The framework will search for the Terraform CLI binary based on the operating system PATH.
          # Eventually, it will use the one we set up above.
          # More information: https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests#terraform-cli-installation-behaviors
        run: |
          go test -v -run '^TestAccKubernetesDeferredActions' ./kubernetes/test-dfa
