name: Golang Linter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/go.mod'

jobs:
  golang_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: 'v1.55.2'
          skip-pkg-cache: true
