name: Manifest unit tests

on:
  push:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
      - "manifest/**/go.mod"
  pull_request:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
      - "manifest/**/go.mod"
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      - name: Go mod verify
        run: go mod verify
      - name: Run unit tests
        run: |
          go test -v -timeout=30s -parallel=4 ./manifest/...
