name: Manifest unit tests

on:
  push:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
      - "manifest/**/go.mod"
  pull_request:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
      - "manifest/**/go.mod"
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
      - name: Go mod verify
        run: go mod verify
      - name: Run unit tests
        run: |
          go test -v -timeout=30s -parallel=4 ./manifest/...
