name: Manifest unit tests

on:
  push:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
  pull_request:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: 'go.mod'
      - name: Go mod verify
        run: go mod verify
      - name: Run unit tests
        run: |
          go test -v -timeout=30s -parallel=4 ./manifest/...
