name: Check Markdown links

on:
  schedule:
    # Run once a week, every Sunday
    - cron: '30 4 * * 0'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Run Markdown links checker
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.15
        with:
          base-branch: main
          config-file: '.github/workflows/markdown.links.config.json'
          file-extension: '.markdown'
          folder-path: 'docs'
          use-verbose-mode: yes
          use-quiet-mode: yes
          max-depth: 2
