name: Check Markdown links

on:
  schedule:
    # Run once a week, every Sunday
    - cron: '30 4 * * 0'
  pull_request:
    branches:
      - main
    paths:
      - 'website/docs/**'
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run Markdown links checker
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.15
        with:
          base-branch: main
          config-file: '.github/workflows/markdown.links.config.json'
          file-extension: '.markdown'
          folder-path: 'website/docs'
          use-verbose-mode: yes
          use-quiet-mode: yes
          max-depth: 2
