name: Provider Functions Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "internal/framework/provider/functions/**/*.go"
  pull_request:
    branches:
      - main
    paths:
      - "internal/framework/provider/functions/**/*.go"
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      - name: Go mod verify
        run: go mod verify
      - name: Run unit tests
        env:
          # FIXME this needs to be changed once the 1.8 release goes out
          TF_ACC_TERRAFORM_VERSION: 1.8.0-rc1
        run: |
          make testfuncs
