on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Run markdown link checker
      uses: gaurav-nelson/github-action-markdown-link-check@0fe4911067fa322422f325b002d2038ba5602170
      with:
        config-file: '.github/workflows/markdown.links.config.json'
        folder-path: 'website/'
  test:
    env:
      GO111MODULE: on
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: ${{ matrix.go-version }}
    # Secrets are not available on pull requests.
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.RO_DOCKERHUB_USER }}
        password: ${{ secrets.RO_DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Install cookie
      run: scripts/gogetcookie.sh
    - name: Run tests
      run: |
        make website-lint
        make depscheck
        make fmtcheck
        make test
        make test-compile
        make tests-lint
        make vet
