on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Run markdown link checker
      uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.15
      with:
        config-file: '.github/workflows/markdown.links.config.json'
        folder-path: 'website/'
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Set up Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: 'go.mod'
    # Secrets are not available on pull requests.
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
      with:
        username: ${{ secrets.RO_DOCKERHUB_USER }}
        password: ${{ secrets.RO_DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Install cookie
      run: scripts/gogetcookie.sh
    - name: Run tests
      run: |
        make website-lint
        make depscheck
        make fmtcheck
        make test
        make test-compile
        make tests-lint
        make vet
