name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/*.go'
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: 'go.mod'
    - name: Run unit tests
      env: 
       TESTARGS: -count 1
      run: |
        make test
